sequenceDiagram
 participant browser
 participant server

 browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
 activate server
 Note left of server: JSON payload: {"content": "New note", "date": "2025-01-30"}

 server->>browser: 201 created
 deactivate server

 Note right of browser: The browser updates the page dynamically with the new note without reloading
